apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: tc-system
type: Opaque
stringData:
  api-token: <CLOUDFLARE_API_TOKEN>
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tysoncloud-issuer
  namespace: tc-system
spec:
  acme:
    email: <CLOUDFLARE_EMAIL>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tysoncloud-issuer-account-key-1
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
