services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    container_name: ollama
    networks:
      - n8n-network
    volumes:
      - ollama_data:/root/.ollama

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    networks:
      - n8n-network
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - WEBHOOK_URL=http://localhost:5678
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - n8n_data:/home/node/.n8n

networks:
  n8n-network:

volumes:
  ollama_data:
  n8n_data:
