events {
  worker_connections 1024;
}

http {

  server {
        listen 80;
        server_name tc.tysoncloud.dev, *.tysoncloud.tysonjenkins.dev;

        location / {
            proxy_pass http://backend-http;

            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name *.home-system.tysonjenkins.dev;

        location / {
            proxy_pass http://home-http;

            proxy_set_header Host $host;
        }
    }

    server {
        listen 443 ssl;
        server_name tc.tysonjenkins.dev;

        ssl_certificate      /etc/letsencrypt/live/tc.tysonjenkins.dev/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/tc.tysonjenkins.dev/privkey.pem;
        ssl_protocols        TLSv1.2 TLSv1.3;

        location / {
                proxy_pass            https://backend;
                proxy_ssl_server_name on;
                proxy_ssl_name        $host;
                proxy_ssl_verify      off;
                proxy_ssl_protocols   TLSv1.2 TLSv1.3;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
     }

       server {
        listen 443 ssl;
        server_name *.home-system.tysonjenkins.dev;

        ssl_certificate      /etc/letsencrypt/live/home-system.tysonjenkins.dev/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/home-system.tysonjenkins.dev/privkey.pem;
        ssl_protocols        TLSv1.2 TLSv1.3;

        location / {
                proxy_pass            https://home;
                proxy_ssl_server_name on;
                proxy_ssl_name        $host;
                proxy_ssl_verify      off;
                proxy_ssl_session_reuse off;
                proxy_ssl_protocols   TLSv1.2 TLSv1.3;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
     }

    server {
        listen 443 ssl;
        server_name *.tysoncloud.tysonjenkins.dev;

        ssl_certificate      /etc/letsencrypt/live/tc.tysonjenkins.dev/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/tc.tysonjenkins.dev/privkey.pem;
        ssl_protocols        TLSv1.2 TLSv1.3;

        location / {
                proxy_pass            https://backend;
                proxy_ssl_server_name on;
                proxy_ssl_name        $host;
                proxy_ssl_verify      off;
                proxy_ssl_session_reuse off;
                proxy_ssl_protocols   TLSv1.2 TLSv1.3;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
     }
}
